[23-May-2021 15:03:08 UTC] PHP Fatal error:  Uncaught Error: Class 'Drupal\Composer\Plugin\VendorHardening\FileSecurity' not found in /home/p5mzzevzpx7l/public_html/mytool/vendor/drupal/core-vendor-hardening/VendorHardeningPlugin.php:369
Stack trace:
#0 /home/p5mzzevzpx7l/public_html/mytool/vendor/drupal/core-vendor-hardening/VendorHardeningPlugin.php(102): Drupal\Composer\Plugin\VendorHardening\VendorHardeningPlugin->writeAccessRestrictionFiles('/home/p5mzzevzp...')
#1 [internal function]: Drupal\Composer\Plugin\VendorHardening\VendorHardeningPlugin->onPostAutoloadDump(Object(Composer\Script\Event))
#2 phar:///opt/cpanel/composer/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(176): call_user_func(Array, Object(Composer\Script\Event))
#3 phar:///opt/cpanel/composer/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#4 phar:///opt/cpanel/composer/bin/composer/src/Composer/Autoload/AutoloadGenerator.php(312): Composer\EventDispatcher\EventDis in /home/p5mzzevzpx7l/public_html/mytool/vendor/drupal/core-vendor-hardening/VendorHardeningPlugin.php on line 369
[23-May-2021 16:39:50 UTC] PDOException: SQLSTATE[42000] [1044] Access denied for user 'i5942845_2021'@'localhost' to database 'i5942845_2021' in /home/p5mzzevzpx7l/public_html/mytool/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/p5mzzevzpx7l/public_html/mytool/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=loca...', 'i5942845_2021', 'i5942845_2021', Array)
#1 /home/p5mzzevzpx7l/public_html/mytool/core/lib/Drupal/Core/Database/Database.php(374): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#2 /home/p5mzzevzpx7l/public_html/mytool/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#3 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#4 /home/p5mzzevzpx7l/public_html/mytool/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#5 /home/p5mzzevzpx7l/public_html/mytool/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#6 /home/p5mzzevzpx7l/public_html/mytool/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#7 /home/p5mzzevzpx7l/public_html/mytool/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#8 /home/p5mzzevzpx7l/public_html/mytool/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#9 /home/p5mzzevzpx7l/public_html/mytool/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\Component\DependencyInjection\Container->get('cache.container')
#10 /home/p5mzzevzpx7l/public_html/mytool/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/p5mzzevzpx7l/public_html/mytool/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/p5mzzevzpx7l/public_html/mytool/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\Core\DrupalKernel->boot()
#13 /home/p5mzzevzpx7l/public_html/mytool/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#14 {main}
[08-Jun-2021 23:16:31 UTC] PHP Fatal error:  Interface 'CommerceGuys\Addressing\AddressInterface' not found in /home/p5mzzevzpx7l/public_html/mytool/modules/contrib/address/src/AddressInterface.php on line 11
